Fix text with leading whitespace parsing
candy-lang/candy pull request #1015
Opened 2024-04-13 19:54 UTC by styrix560

Closes: #896

### Checklist

- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

2024-04-13 20:06 UTC, JonasWanke requested changes

2024-04-13 20:06 UTC, JonasWanke commented on compiler/vm/src/heap/mod.rs
> +        println!("{:?}", self.objects);
```suggestion
```

2024-04-13 20:06 UTC, JonasWanke commented on compiler/frontend/src/string_to_rcst/text.rs
> +
I'd move the blank line above because this and the `if`/`else` below belong together

```suggestion

    let (new_input, mut opening_whitespace) =
        whitespaces_and_newlines(input, indentation + 1, false);
```

2024-04-13 20:06 UTC, JonasWanke commented on compiler/frontend/src/string_to_rcst/text.rs
> +    // this fixes issue #896
```suggestion
    // If the string does not contain any newlines, parse the whitespace in
    // front of the string as part of the string and not as trailing whitespace.
    // This fixes https://github.com/candy-lang/candy/issues/896.
```

2024-04-14 08:55 UTC, styrix560 commented
I messed up with the merge. I will fix this and request another review

2024-04-18 10:18 UTC, JonasWanke approved these changes

2024-04-18 10:18 UTC, merged