Add compiler CI
candy-lang/candy pull request #236
Opened 2022-07-29 11:28 UTC by JonasWanke

2022-07-31 09:09 UTC, MarcelGarus approved these changes

2022-07-31 09:09 UTC, MarcelGarus commented on compiler/src/compiler/string_to_rcst.rs
> +        input.strip_prefix(literal)
Whoa, was that detected by clippy? Impressive!

2022-07-31 09:22 UTC, MarcelGarus commented
About the reported lints:

- Regarding `CallReceiver`: What exactly is the benefit of using that over just storing an arbitrary `Ast` expression? Like, sure, we'll find out in the AST that the call is invalid if the receiver is just an int literal or something like that, but we would also find that during constant evaluation. So, in terms of developer experience, it's not really a difference.
  Actually, in the next stage of the compiler pipeline, the AST-to-HIR conversion, we don't actually use the receiver information in a meaningful way: After special-casing the calling of a  `AstIdentifier::("needs")`, we just match over the receiver type, and if it's a `StructAccess`, we call `lower_struct_access`, if it's a `Call`, we call `lower_call`, and if it's an `Identifier`, we essentially have a copied version of the `compile_single`' code for lowering an `Identifier`. We could just as easily treat all receivers the same (just `compile_single` them directly).
- Regarding modules with the same name: I think it makes sense to ignore this lint. For example, I like that modules can have local `utils` modules without polluting some outer scope.
- Regarding the `to_*` methods: I guess it makes sense to rename them then.
- Few unused methods: That's probably okay for now. Some of them, such as `Hir::return_value`, at least feel like they could become useful later on. But in the long term, ofc it makes sense to clean these up too.

2022-07-31 17:13 UTC, JonasWanke commented
Regarding the modules with the same name: I think my explanation wasn't clear, so here's a link to the lint: https://rust-lang.github.io/rust-clippy/master/index.html#module_inception. The problem is module `fuzzer` _inside_ module `fuzzer`

2022-07-31 21:09 UTC, MarcelGarus requested changes

2022-07-31 21:09 UTC, MarcelGarus commented on compiler/src/compiler/cst_to_ast.rs
>                  };
Doesn't the same reasoning that motivated the removal of a `CallReceiver` also apply here? i.e. not special-casing based on the type of the receiver and just doing `let receiver = self.lower_cst(name);` That would also allow for `lower_identifier` and `lower_struct_access` to be inlined.

Sidenote: It probably also makes sense to rename `CstKind::Call`'s `name` to `receiver`.

2022-07-31 21:15 UTC, MarcelGarus commented
Regarding the `module_inception` lint: That's a fair concern, I agree that having both a `mod.rs` and `fuzzer.rs` in `fuzzer` is kinda weird. We could merge both into the `mod.rs` file, but they _do_ contain different logic (the CLI and exports vs. the actual fuzzing logic).

In the best case, I think we'd rename the `fuzzer.rs` to something else, but I'm having a hard time finding a fitting name. We could try to go for a name that describes the module's role _within_ the fuzzer, i.e. `engine` or something like that. What do you think?

2022-08-03 10:51 UTC, MarcelGarus approved these changes

2022-08-03 10:52 UTC, merged

2022-08-03 10:52 UTC, MarcelGarus commented
Just noticed that the term `receiver` probably stems from object-oriented programming languages, where method invocations are implemented using message passing and a better term in Candy would probably be `callee`. But we can change that later.