Make builtin functions more lightweight
candy-lang/candy pull request #239
Opened 2022-08-07 13:39 UTC by MarcelGarus

Standard logging can get confusing when used with async/await because a series of events doesn't have to be connected. This PR adds structured logging using the [tracing create](https://crates.io/crates/tracing), which is a de-facto standard for structured logging and is also supported by salsa.

Like with usual logging, you can use the `info!` etc. macros to emit events. But it also supports _spans_, which log ongoing operations. All events logged within a span then contain the span for context. This is also useful for debugging our parser because we can actually look at the parser stack:

![image](https://user-images.githubusercontent.com/8601189/183293422-de121fa2-e482-4140-a6bd-1564aee2faa7.png)

2022-08-07 15:22 UTC, MarcelGarus commented
The remaining elephant in the room is the copying of instructions – the flamegraph is dominated by clones and drops of instructions (or closures, which contain lots of instructions).

Apart from that, the VM is now reasonably fast – at least, there are no obvious parts where we have too much algorithmic complexity (such as the `Value` before) or do unnecessary work (such as with the logging).
This is supported by numbers: Our VM currently executes `use "..Core"` in ~100 ms, excluding the compilation of files (at least kind of, I assume that compilation doesn't play a huge part when averaging over hundred invocations, 99 of which don't need to compile anything new and are served by salsa). A `use "..Core"` corresponds to ~80000 instructions, so this corresponds to about 800 instructions per second.

Regarding performance, the next sensible step is probably to do some basic optimizations on the intermediary representations (aka reduce the number of instructions from 80000 to a lower number by doing some compile-time evaluation including caching, eliminating common subtrees, inlining functions, etc.)
The optimization with the potentially biggest payoff is using compile-time evaluation to simplify code. However, I suggest we delay further optimizing the VM until after we implemented fibers and channels (i.e. we model side-effects explicitly). Otherwise, _everything_ would get optimized into one struct containing all definitions, which makes sense, but is not really representative of real-world use-cases.

2022-08-26 08:52 UTC, JonasWanke requested changes

2022-08-26 08:52 UTC, JonasWanke commented on compiler/src/fuzzer/mod.rs
> +                tracer.dump_stack_trace(db, heap);
What do you think about lowering the severity to `info`? It's not an actual error of our compiler, but just an error in the user's code that got discovered

2022-08-26 08:52 UTC, JonasWanke commented on compiler/src/main.rs
> +        if metadata.module_path().unwrap_or("").starts_with(module) {
```suggestion
        if metadata.module_path().unwrap_or_default().starts_with(module) {
```

2022-08-27 08:47 UTC, JonasWanke approved these changes

2022-08-27 08:48 UTC, JonasWanke commented
(But Clippy complains about an unused import)

2022-08-29 16:22 UTC, merged