Add fuzzing to the CI
candy-lang/candy pull request #246
Opened 2022-10-19 22:02 UTC by MarcelGarus

Depends on #245

This makes the exit code of the `candy fuzz` command match whether errors were found during fuzzing. It also adds fuzzing to the CI and fixes some errors that were discovered.

2022-10-19 22:13 UTC, MarcelGarus commented
You may have noticed that the functions in `Core` are fuzzed several times. That's because the tree of modules created from `Core/_.candy` contains the outer leaf files many times. For example, the `core.bool` module is imported by many other modules in the core package, causing it to be instantiated and evaluated many times. All the created closures are separate and fuzzed independently.

I guess I'll start working on some basic optimizations soon such as function inlining, duplicate subtree elimination, and compile-time evaluation. The two last ones in particular would fix the problem described above. LLVM would also do those optimizations, but we'd have to turn the entire tree (including duplicated expanded use stuff) into LLVM-IR for it to do its magic, so that's too late in the pipeline.

2022-11-03 20:09 UTC, JonasWanke requested changes
Rust also has a few complaints:

![image](https://user-images.githubusercontent.com/19330937/199824010-5e8569f3-910d-47ad-b11f-475db22cca9e.png)

2022-11-03 20:09 UTC, JonasWanke commented on packages/Benchmark.candy
> +fib = { n -> fibRec fibRec n }
```suggestion
fib n =
  needs (core.int.is n)
  fibRec fibRec n
```

2022-11-03 20:09 UTC, JonasWanke commented on packages/Core/int.candy
> +fitsInRustU32 value =
```suggestion
fitsInRustU32 value :=
```

2022-11-03 20:09 UTC, JonasWanke commented on .github/workflows/compiler.yaml
> +          components: clippy
I don't think we need Clippy for fuzzing

```suggestion
```

2022-11-03 20:09 UTC, JonasWanke commented on compiler/src/main.rs
> +        }
Blub

2022-11-10 21:47 UTC, MarcelGarus commented
Fuzzing works fine locally. Seems like this is an issue of nightly cargo: https://github.com/rust-lang/cargo/issues/8557

2022-11-10 22:03 UTC, JonasWanke reviewed
I'm not sure whether the issue you linked is really related since it's been closed for more than two years, but I couldn't find a good-looking current one. Maybe we should disable the action for now so that we don't get used to the failing CI?

2022-11-10 22:12 UTC, MarcelGarus commented
Fair enough, I'll just disable the fuzzing for now

2022-11-11 07:11 UTC, JonasWanke approved these changes

2022-11-11 09:24 UTC, merged