Implement heap using `Vec`
candy-lang/candy pull request #268
Opened 2023-01-13 11:02 UTC by JonasWanke

Performance improvements: https://github.com/candy-lang/candy/commit/fcf1f1ec9da4010e86850dabae30e056c67ddf0d (almost 60 %) and https://github.com/candy-lang/candy/commit/02a4a9131d5938753d7eb75a9a89120f0aef72ee (minimal change)

### Checklist

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

2023-01-13 20:41 UTC, MarcelGarus requested changes

2023-01-13 20:41 UTC, MarcelGarus commented on .github/workflows/compiler.yaml
> +          auto-push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && true || false }}
Why the `&& true || false`?

2023-01-16 17:31 UTC, JonasWanke commented
I'm not sure what's going on with GitHub here, but I pushed a commit to address the requested change. It appears in the network tab and is shown on the branch, but is not shown here or in the PR's commit tab. https://github.com/candy-lang/candy/commit/d23ee0e4feadf04dced1cea0e052fc75aa900dbf

2023-01-19 13:53 UTC, MarcelGarus approved these changes

2023-01-19 14:06 UTC, merged