Or patterns
candy-lang/candy pull request #280
Opened 2023-02-03 15:52 UTC by JonasWanke

Don't use them yet; values captured in identifiers can be in an incorrect order. I'll work on improving our debugging tools first to better debug this

### Checklist

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

2023-02-03 21:16 UTC, MarcelGarus requested changes

2023-02-03 21:16 UTC, MarcelGarus commented on compiler/src/compiler/string_to_rcst.rs
> +            let Some((new_input, bar)) = bar(new_input) else { break  };
```suggestion
            let Some((new_input, bar)) = bar(new_input) else { break };
```

2023-02-03 21:16 UTC, MarcelGarus commented on compiler/src/compiler/hir_to_mir.rs
> +                dbg!(&captured_identifiers_order);
```suggestion
```

2023-02-03 21:16 UTC, MarcelGarus commented on compiler/src/compiler/hir_to_mir.rs
> +                            dbg!(&captured_identifiers);
```suggestion
```

2023-02-03 21:16 UTC, MarcelGarus commented on compiler/src/compiler/hir_to_mir.rs
> +                                        dbg!(identifier_id);
```suggestion
```

2023-02-03 21:16 UTC, MarcelGarus commented on compiler/src/compiler/hir_to_mir.rs
> +                                                dbg!(index);
```suggestion
```

2023-02-03 21:16 UTC, MarcelGarus commented on compiler/src/compiler/hir_to_mir.rs
> +                                                    self.responsible,
Also, the code is very far indented here. If you know a way to fix it, sure, otherwise this is fine

2023-02-06 09:17 UTC, MarcelGarus approved these changes

2023-02-06 09:18 UTC, merged

2023-02-07 11:07 UTC, MarcelGarus commented
Just wondering: It is safe to use or patterns while not capturing identifiers, right?

i.e. `True | False`

2023-02-07 11:49 UTC, JonasWanke commented
Yes, I didn't find bugs in those