Fix some bugs and make core package richer
candy-lang/candy pull request #328
Opened 2023-02-10 10:15 UTC by MarcelGarus

This PR adds some features to the core package. It also fixes bugs that were discovered while doing this and while fuzzing the compiler.

2023-02-10 22:13 UTC, JonasWanke requested changes

2023-02-10 22:13 UTC, JonasWanke commented on compiler/frontend/src/hir_to_mir.rs
> +                    let pattern_result = body.push_reference(pattern_result);
Do we actually have to push this reference? Subsequent `PatternIdentifierReference`s will refer to the correct ID using `self.ongoing_destructuring` and a `Nothing` will follow so it also can't be the surrounding body's return value

2023-02-10 22:13 UTC, JonasWanke commented on packages/Core/controlFlow.candy
> +  needs (function.is0 body)
In Kotlin, the `body` accepts the repetition index as a parameter. We could even support `function.is0` _and_ `function.is1` here, but could also say that if you need the index, you should create a range (once we have that)

2023-02-10 22:13 UTC, JonasWanke commented on packages/Core/mutable.candy
> +    await finalValue
Couldn't we remove the `async`/`await` around here and call `recursive` directly?

2023-02-22 16:02 UTC, MarcelGarus commented on packages/Core/controlFlow.candy
> +  needs (function.is0 body)
I like the option of explicitly specifying a range.

2023-02-22 16:09 UTC, MarcelGarus commented on compiler/frontend/src/hir_to_mir.rs
> +                    let pattern_result = body.push_reference(pattern_result);
I simplified the code a bit by just returning a nothing. We could further simplify the HIR by just not pushing anything at all for this expression, but it makes the rest of this function more complicated (we'd need the expression compilation to produce an `Option<Id>` everywhere).

Considering that tree shaking is a thing, I'm fine with the current solution.

2023-02-23 11:21 UTC, JonasWanke requested changes

2023-02-23 11:21 UTC, JonasWanke commented on compiler/frontend/src/hir_to_mir.rs
> +                    body.push_nothing()
By moving the `self.ongoing_destructuring = …` above `body.push_if_else(…)`, we can get rid of the `body.push_nothing()`

2023-02-23 15:16 UTC, JonasWanke approved these changes

2023-02-23 15:16 UTC, merged