Generate debug files (as read-only VS Code views)
candy-lang/candy pull request #335
Opened 2023-02-13 19:01 UTC by JonasWanke

Closes: #307

Only AST and RCST are implemented at all, and these are also just initial implementations.

![image](https://user-images.githubusercontent.com/19330937/218549644-ad1286ff-3615-431a-8e78-ba59f2d5389a.png)

![image](https://user-images.githubusercontent.com/19330937/218549720-44e8791a-60a9-42bf-b385-55a2239b26dd.png)

### Checklist

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

2023-02-13 21:52 UTC, MarcelGarus requested changes

2023-02-13 21:52 UTC, MarcelGarus commented on compiler/frontend/src/rich_ir.rs
> +pub enum TokenModifier {}
What's this for?

2023-02-13 21:52 UTC, MarcelGarus commented on compiler/frontend/src/ast.rs
> +            format!(" int {}", self.0),
```suggestion
            format!("int {}", self.0),
```

2023-02-13 21:52 UTC, MarcelGarus commented on compiler/language_server/src/features_candy/mod.rs
> +        // let (hints_sender, mut hints_receiver) = tokio::sync::mpsc::channel(1024);
```suggestion
```

2023-02-13 21:52 UTC, MarcelGarus commented on compiler/language_server/src/features_candy/mod.rs
> +        Self: 'async_trait,
```suggestion
    fn semantic_tokens<'self, 'db, 'async_trait>(
        &'self self,
        db: &'db Database,
        module: Module,
    ) -> Pin<Box<dyn Future<Output = Vec<SemanticToken>> + Send + 'async_trait>>
    where
        'self: 'async_trait,
        'db: 'async_trait,
        Self: 'async_trait,
```

2023-02-13 21:52 UTC, MarcelGarus commented on compiler/language_server/src/server.rs
> +            // };
Is this still needed?

2023-02-14 09:01 UTC, JonasWanke commented on compiler/language_server/src/features_candy/mod.rs
> +        Self: 'async_trait,
`self` is a reserved name and can't be used as a lifetime name. Also, the names have to be the same as in the trait itself, so we can't change them here without also having to manually define the async function there

2023-02-14 10:23 UTC, MarcelGarus approved these changes

2023-02-14 10:39 UTC, merged