More rich ir features
candy-lang/candy pull request #353
Opened 2023-02-27 10:07 UTC by JonasWanke

- “Find references” works across all opened IRs
- “Go to definition” works for modules
- “Go to definition” on a HIR ID opens that HIR if it's not open already
- <kbd>Ctrl</kbd>+click on the span of a compiler error within an opened IR to navigate to the source code:
  ![image](https://user-images.githubusercontent.com/19330937/221533985-ccff6d56-4113-4832-923e-efd829103abd.png)

### Checklist

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

2023-02-27 11:09 UTC, JonasWanke commented
The CI is only failing due to https://github.com/clap-rs/clap/issues/4733

2023-03-02 09:47 UTC, MarcelGarus requested changes

2023-03-02 09:47 UTC, MarcelGarus commented on compiler/language_server/src/features_ir.rs
> +                ModuleKind::Code, // FIXME
.

2023-03-02 10:16 UTC, MarcelGarus approved these changes

2023-03-02 10:16 UTC, merged