Unify CST and RCST
candy-lang/candy pull request #361
Opened 2023-03-06 13:44 UTC by JonasWanke

### Checklist

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

2023-03-07 09:30 UTC, MarcelGarus requested changes
I didn't look at `string_to_rcst` in too much detail, but it should be fine.

What also came to my mind: If we implement a `children` method on the CST that returns an `impl Iterator<Item =&Cst>`, some of the utility methods can be implemented in a much simpler way. For example `is_multiline`:

```
fn is_multiline(&self) -> bool {
  match self.kind {
    CstKind::Newline(_) => true,
    other => other.children.any(|child| child.is_multiline()),
  }
}
```

Same goes for display, finding IDs, etc.

2023-03-07 09:30 UTC, MarcelGarus commented on compiler/frontend/src/cst/error.rs
> +    PipeMissesCall,
I know you only moved the code here, but we should probably rename these as the CST doesn't know the semantic of bars.

2023-03-07 09:30 UTC, MarcelGarus commented on compiler/frontend/src/cst/mod.rs
> +mod unwrap_whitespace_and_comment;
We usually sorted the `mod` parts before the `use`s. But if this is auto-inserted like this, I won't complain.

2023-03-07 09:30 UTC, MarcelGarus commented on compiler/frontend/src/cst/error.rs
> +    PipeMissesCall,
Oh, also some errors use `Without`, some use `Missing`. But we can fix that in another PR

2023-03-07 09:30 UTC, MarcelGarus commented on compiler/language_server/src/features_candy/find_definition.rs
> +    let origin_hir_id = db.cst_to_hir_id(module.clone(), origin_cst.data.id)?;
If we also implement `Deref` for the CST, can this be removed?

2023-03-07 17:39 UTC, JonasWanke commented on compiler/frontend/src/cst/mod.rs
> +mod unwrap_whitespace_and_comment;
When I manually touched them, I put `mod`ule declarations _after_ `use`s^^ The only official statement I can find about this topic is:

> We recommend that imports come before module declarations; […]
>
>https://github.com/rust-lang/style-team/blob/02f3c00c06c6609e3e0add3f2f15f448e12b709a/guide/items.md?plain=1#L6-L8

I'm not sure in which order they get inserted automatically, and am a bit disappointed that rustfmt doesn't reorder them. Relevant issues: https://github.com/rust-lang/rustfmt/issues/4741, https://github.com/rust-lang/rustfmt/issues/3959

2023-03-07 17:41 UTC, JonasWanke commented on compiler/language_server/src/features_candy/find_definition.rs
> +    let origin_hir_id = db.cst_to_hir_id(module.clone(), origin_cst.data.id)?;
We do implement `Derive` for `Cst` (using [<kbd>derive_more</kbd>](https://crates.io/crates/derive_more)), but `.data` is still necessary here. I'm assuming that `Deref`-ing only works for method calls and not field accesses

2023-03-07 17:49 UTC, JonasWanke commented on compiler/frontend/src/cst/error.rs
> +    PipeMissesCall,
Do you have a preference for either of the names?

2023-03-07 17:56 UTC, JonasWanke commented
Unfortunately, `pub fn children(&self) -> impl Iterator<Item = &Cst<D>>` is not that easy since, despite the `impl …`, all `match` arms still have to return the same iterator type. Hence, I'd move that to a separate PR (if it's even viable)

2023-03-07 18:14 UTC, MarcelGarus commented on compiler/frontend/src/cst/error.rs
> +    PipeMissesCall,
I think I prefer "misses" as it more clearly communicates there's an error

2023-03-07 18:14 UTC, MarcelGarus commented on compiler/frontend/src/cst/error.rs
> +    PipeMissesCall,
I think I prefer "misses" as it more clearly communicates there's an error

2023-03-07 18:16 UTC, MarcelGarus approved these changes

2023-03-08 16:05 UTC, JonasWanke commented
Looks like at least some cargo commands in our CI were checking the whole workspace when we executed them for a single crate. I now unified invocations per crate into one invocation each to avoid this. This also reduces our CI time

2023-03-08 16:51 UTC, MarcelGarus approved these changes

2023-03-08 18:45 UTC, merged