Add Random
candy-lang/candy pull request #37
Opened 2020-11-18 18:36 UTC by JonasWanke

2020-11-18 22:16 UTC, marcelgarus requested changes

2020-11-18 22:16 UTC, MarcelGarus commented on packages/core/src/random/source.candy
> +builtin impl DefaultRandomSource: RandomSource
Do we really want to expose `DefaultRandomSource` to the rest of the Candy ecosystem, or should we rather provide static methods on `RandomSource`, as in `RandomSource.default()` and `RandomSource.defaultWithSeed(...)`?

2020-11-18 22:16 UTC, MarcelGarus commented on packages/core/src/random/source.candy
> +  // fun generateBytes(length: Int): List<Int>
I'm not sure about this one. I think we should offer randomness at smaller granularities:
- `generateBool` for generating a bit
- `generateByte` for generating a byte
- `generateBytes` for generating an arbitrary number of bytes

Of course, for now, the byte generators could return `int`s up to 255 instead.

Some advantages:

- We could provide default implementations for everything except `generateBool`. That makes it very easy to implement `RandomSource` while keeping the option to write more efficient `RandomSource`s. ("Very easy" as in "just write a method that returns `true` 50% of the time".)
- Providing randomness on bit granularity also has the advantage that we are more careful about using up entropy. When we implement a secure `RandomSource`, we'll probably use something like /dev/random on Linux and we could use bitshifting to give out single bits of entropy. That seems especially useful for generating bools and enum variants without consuming a whole byte of entropy every time.

That being said, I'm also okay with `generateByte` being the one without a default implementation. Most implementations work on byte-granularity anyways and for those that are extra careful about using entropy, they can implement `generateBool` too. For example, our default number generator probably doesn't need a special `generateBool`, but the secure one does.

2020-11-18 22:16 UTC, MarcelGarus commented on packages/compiler/lib/src/compilation/hir/type.dart
> +  // reflection
```suggestion
  // random
```

2020-11-29 10:15 UTC, JonasWanke commented on packages/core/src/random/source.candy
> +builtin impl DefaultRandomSource: RandomSource
It's private already

2020-11-29 11:19 UTC, JonasWanke commented on packages/core/src/random/source.candy
> +  // fun generateBytes(length: Int): List<Int>
It's now changed to provide the three methods mentioned above, with `generateByte` being the default used by the other two.

2020-11-29 11:31 UTC, marcelgarus approved these changes

2020-11-29 11:31 UTC, merged