Add Tags
candy-lang/candy pull request #394
Opened 2023-04-17 11:24 UTC by skyz1

Closes: #282 

This PR allows symbols to be associated with a value by calling them with that value.
![image](https://user-images.githubusercontent.com/81387843/232469902-bd2c7757-5799-4033-a351-a19a8afa787f.png)

### Checklist

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

2023-04-18 12:52 UTC, MarcelGarus requested changes

2023-04-18 12:52 UTC, MarcelGarus commented on compiler/frontend/src/builtin_functions.rs
> +    TagGetSymbol,        // symbol -> symbol
To the user, I wouldn't even mention the word symbol and instead, use tags consistently (which either have values or don't). This builtin could then be named `tagWithoutValue` (or something like that).

I'd also rename the other references here (for example, change the comment of `structHasKey` to `struct key -> booleanTag`).

Of course, the rest of our internal compiler code would continue to use "symbol" like it already does.

2023-04-18 12:52 UTC, MarcelGarus commented on packages/Core/tag.candy
> +  ifElse (valueTag | hasValue) { tag (valueTag | getValue) } { tag | getSymbol }
I would have expected this to take a tag and a value, for example, `tag.withValue Foo 5` (= `Foo 5`) or `tag.withValue (Foo 2) 3` (= `Foo 3`).

2023-04-18 13:05 UTC, JonasWanke requested changes

2023-04-18 13:05 UTC, JonasWanke commented on compiler/frontend/src/builtin_functions.rs
> +    TagGetValue,         // symbol -> any
Please keep them ordered alphabetically

2023-04-18 13:05 UTC, JonasWanke commented on compiler/vm/src/heap/mod.rs
> +    pub fn create_tag(&mut self, symbol: String, value: Option<Pointer>) -> Pointer {
By slightly modifying the argument type, this function can also be called with a `Pointer` directly since any `T` `impl`s `Into<Option<T>>`:

```suggestion
    pub fn create_tag(&mut self, symbol: String, value: impl Into<Option<Pointer>>) -> Pointer {
```

2023-04-18 13:05 UTC, JonasWanke commented on compiler/vm/src/fiber.rs
> +                    self.heap.dup(*value);
I think that this should error when trying to overwrite the tag's current value. We could then point the user to use `tag.withValue` instead

2023-04-18 13:05 UTC, JonasWanke commented on compiler/vm/src/fiber.rs
> +                            "Assigning the value of a tag expects 1 parameter, but you provided {} arguments.",
```suggestion
                            "A tag can only hold exactly one value, but you called it with {} arguments.",
```

2023-04-18 13:05 UTC, JonasWanke commented on compiler/vm/src/heap/object.rs
> +                format!("{}({})", symbol, value.format_helper(heap, is_debug))
To stay closer to the source code, I'd add a whitespace before the parentheses. We can add a smarter stringification later on that tracks precedence so that parentheses are only added where necessary

```suggestion
                format!("{} ({})", symbol, value.format_helper(heap, is_debug))
```

2023-04-18 13:05 UTC, JonasWanke commented on compiler/vm/src/lir.rs
> +    /// Pushes a empty tag.
```suggestion
    /// Pushes an empty tag.
```

2023-04-18 13:05 UTC, JonasWanke commented on packages/Core/tag.candy
> +[ifElse] = use "..controlFlow"
We order imports alphabetically by path:

```suggestion
[ifElse] = use "..controlFlow"
type = use "..type"
```

2023-04-23 07:40 UTC, JonasWanke approved these changes

2023-04-23 16:02 UTC, MarcelGarus requested changes

2023-04-23 16:02 UTC, MarcelGarus commented on compiler/vm/src/fiber.rs
> +                        "A tags value cannot be overwritten by calling it. Use tag.withValue instead.".to_string(),
```suggestion
                        "A tag's value cannot be overwritten by calling it. Use `tag.withValue` instead.".to_string(),
```

2023-04-23 16:05 UTC, JonasWanke commented on packages/Core/tag.candy
> +  tagWithoutValue value
I just fixed this in #404

```suggestion
  (tag | withoutValue) value
```

2023-04-24 21:54 UTC, MarcelGarus approved these changes

2023-04-25 17:55 UTC, merged