CST-AST-lowering of types and declarations
candy-lang/candy pull request #58
Opened 2021-01-21 19:53 UTC by JonasWanke

2021-01-24 12:13 UTC, marcelgarus requested changes
Nice to see progress!

2021-01-24 12:13 UTC, MarcelGarus commented on packages/ast/src/declarations.candy
> +  public let type: Maybe<AstType>
Don't you always have to provide a type?

2021-01-24 12:13 UTC, MarcelGarus commented on packages/ast/src/declarations.candy
> +  public let name: Maybe<AstIdentifier>
Doesn't a module always need a name?

2021-01-24 12:13 UTC, MarcelGarus commented on packages/ast/src/declarations.candy
> +  public let name: Maybe<AstIdentifier>
A trait should always have a name

2021-01-24 12:13 UTC, MarcelGarus commented on packages/ast/src/declarations.candy
> +  public let traits: List<AstNamedType>
Didn't we decide on disallowing multiple (comma-separated) types in favor of intersection types?
```
impl Foo: Bar & Baz
```
instead of 
```
impl Foo: Bar, Baz
```

2021-01-24 12:13 UTC, MarcelGarus commented on packages/ast/src/declarations.candy
> +  public let name: Maybe<AstIdentifier>
Should always have a name

2021-01-24 12:13 UTC, MarcelGarus commented on packages/ast/src/errors/duplicate_declaration_name.candy
> +    if node.child is CstProperty { return node.cast<CstProperty>().child.name.unwrap().child.span }
Okay for now. In the long term, a `HasName` trait or something like that would be useful.

2021-01-24 12:13 UTC, MarcelGarus commented on packages/ast/src/declarations.candy
> +  public let name: Maybe<AstIdentifier>
Functions always have a name

2021-01-24 12:13 UTC, MarcelGarus commented on packages/ast/src/declarations.candy
> +  public let name: Maybe<AstIdentifier>
Value parameters always have a name

2021-01-24 12:13 UTC, MarcelGarus commented on packages/ast/src/declarations.candy
> +  public let name: Maybe<AstIdentifier>
Properties always have a name

2021-01-24 12:13 UTC, MarcelGarus commented on packages/ast/src/errors/invalid_declaration_type.candy
> +    }
A `HasKeyword` trait would be useful. We could simply do `node.cast<HasKeyword>().child.keyword().child.span`.

2021-01-24 12:13 UTC, MarcelGarus commented on packages/ast/src/errors/missing_function_value_parameters.candy
> +  public fun title(): String { "Missing function value parameters string interpolation." }
```suggestion
  public fun title(): String { "Missing function value parameters." }
```

2021-01-24 12:13 UTC, MarcelGarus commented on packages/ast/src/types.candy
> +  public let name: Maybe<AstIdentifier>
Always has a name

2021-01-24 12:13 UTC, MarcelGarus commented on packages/ast/src/types.candy
>  impl AstTypeArgumentId: AstNodeId
What exactly do we need this for? Aren't the `AstType`s inlined in the declaration?

2021-01-24 12:13 UTC, MarcelGarus commented on packages/core/src/collections/map/module.candy
> +      if selector(entry.first, entry.second) { remove(entry.first) }
Lucky us that we don't have a concurrent modification exception yet. 😅

2021-01-24 12:13 UTC, MarcelGarus commented on packages/ast/src/lowering.candy
> +  }
If we would contain a stack of scopes containing the `parentId`s and `previousNames` into the `LoweringContext`, we could add a `Lowerable` trait (or something similar) implemented by `CstFile`, `CstModule`, `CstFunction` etc. so that we could do `cst.lower(context)` instead of doing manual dispatch based on the type.

2021-01-24 12:13 UTC, MarcelGarus commented on packages/ast/src/lowering.candy
> +  }
If we had a `flatten` method on `Maybe<Maybe<T>>`, we could have simply done:
```suggestion
  let initializer = cst.child.initializer.flatMap<AstExpression>({ initializer =>
    initializer.child.expression
      .map<Maybe<AstExpression>>({ lowerExpression(context, id, it) })
      .orElse({
        context.addError(
          ExpectedExpressionCompilerError(
            context.file,
            initializer.cast<CstExpressionBody | CstDelegationBody>(),
          ),
        )
      })
      .flatten()
  })
```
But we can still use map-orElse instead of the outer if.

2021-01-24 12:13 UTC, MarcelGarus commented on packages/ast/src/lowering.candy
> +      }
Maybe a `do` method on `Maybe` would be useful:
```suggestion
      result.do({
        declarations.append(
          it as AstModule | AstTrait | AstImpl | AstClass | AstFunction | AstProperty,
        )
      })
```

2021-01-24 12:13 UTC, MarcelGarus commented on packages/ast/src/lowering.candy
> +  }
This has been a rollercoaster to read: First, a `name` is created, but it's only used for the `id` and then later overwritten by another name variable. Here's a simpler version (also, no `unwrap` is necessary):
```suggestion
  let id = AstDeclarationId(
    parentId,
    cst.child.name
      .map<String>({ it.child.identifier })
      .orElse({ "unnamed-module-{context.getUnnamedDeclarationIndex()}" })
  )
  let modifiers = lowerModifiers(context, id, cst.child.modifiers)
  let name = cst.child.name.map<AstIdentifier>({
    let identifierId = AstIdentifierId(id, 0)
    context.addIdMapping(it.id, identifierId)
    if previousNames.containsKey(it.child.identifier) {
      context.addError(
        DuplicateDeclarationNameCompilerError(
          context.file,
          cst.cast<CstModule | CstTrait | CstClass | CstProperty>(),
        ),
      )
    }
    AstIdentifier(identifierId, it.child.identifier)
  })
  if name is None {
    context.addError(MissingDeclarationNameCompilerError(context.file, cst.cast<CstDeclaration>()))
  }
```
Of course, this also applies to all cases where this code has been copied to.

2021-01-24 12:13 UTC, MarcelGarus commented on packages/ast/src/lowering.candy
> +  }
```suggestion
  let expression = cst.child.expression
    .map<AstExpression>({ lowerExpression(context, parentId, it) })
  if expression is None {
    context.addError(
      ExpectedExpressionCompilerError(
        context.file,
        cst.cast<CstExpressionBody | CstDelegationBody>(),
      ),
    )
  }
```

2021-01-24 12:13 UTC, marcelgarus commented on packages/ast/src/lowering.candy
> +      }
Could be rewritten if we had `Maybe.do`:
```suggestion
      lowered.do({
        result.append(it)
        it.name.do({ previousNames.set(it.value, true) })
      })
```

2021-01-24 12:13 UTC, marcelgarus commented on packages/ast/src/lowering.candy
> +      0,
Ooof.
Maybe comments after the zeros?

2021-01-24 12:24 UTC, JonasWanke commented on packages/ast/src/declarations.candy
> +  public let traits: List<AstNamedType>
Yes. The parser just tries to parse any type. When lowering to the AST, we already check that this type is a named type or an intersection of named types, and flatten these into a list. Hence, the list doesn't contain arbitrary types, but only named types.

2021-01-25 17:16 UTC, JonasWanke commented on packages/ast/src/lowering.candy
> +  }
I'm not sure if a stack of scopes is worth it right now. To allow for type-safe access of the parent scope we'd need a type parameter in context declaring the parent node's type. Maybe we can postpone this refactor until we have a better compiler?

2021-01-25 17:38 UTC, JonasWanke commented on packages/ast/src/types.candy
>  impl AstTypeArgumentId: AstNodeId
Not quite sure what you mean by that. Is it about the existence of `AstTypeArgumentId` or this change?

2021-01-25 19:22 UTC, marcelgarus commented on packages/ast/src/types.candy
>  impl AstTypeArgumentId: AstNodeId
Yes, the existence of `AstTypeArgumentId`.

2021-01-25 20:40 UTC, marcelgarus approved these changes

2021-01-25 20:40 UTC, MarcelGarus commented on packages/ast/src/lowering.candy
> +  }
Sure

2021-01-25 20:40 UTC, merged