Golden tests
candy-lang/candy pull request #580
Opened 2023-07-22 12:20 UTC by JonasWanke

Closes: #522

### Checklist

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

2023-07-23 10:04 UTC, MarcelGarus requested changes

2023-07-23 10:04 UTC, MarcelGarus commented on compiler/cli/src/debug.rs
> +                .visit_irs(db, |_file, _ir_namee, ir_file, ir| {
```suggestion
                .visit_irs(db, |_file, _ir_name, ir_file, ir| {
```

2023-07-23 10:04 UTC, MarcelGarus commented on compiler/cli/src/debug.rs
> +            let lir = address_regex.replace_all(&lir.text, "<removed address>");
Just want to note that the regex may also match other stuff in the Candy code, such as parts of HIR IDs or strings, so there can definitely be false positives:

```candy
foo0xdeadbeef := "my favorite color is 0x71ec4f"
```

```candy
# Constant heap
:
<removed address>: "Foo<removed address>"
<removed address>: "my favorite color is <removed address>"
<removed address>: Examples:playground
<removed address>: Foo<removed address>
<removed address>: [67941FF82BC263AF → Foo<removed address>: "my favorite color is <removed address>"]
<removed address>: { 0 arguments (capturing nothing) → ip-0 }

# Instructions
# Examples:playground
:
0: pushConstant <removed address> [67941FF82BC263AF → Foo<removed address>: "my favorite color is <removed address>"]
1: popMultipleBelowTop 1
2: return
```

But false positives aren't too big of an issue I guess.

2023-07-23 10:04 UTC, MarcelGarus commented on packages/.vscode/launch.json
> +      "program": "${workspaceFolder}/Cxamples/fibonacci.candy"
```suggestion
      "program": "${workspaceFolder}/Examples/fibonacci.candy"
```

2023-07-23 10:04 UTC, MarcelGarus commented on packages/Examples/.goldens/echo.candy/Optimized MIR.txt
> +$10 = Builtins:
The HIR IDs get broken up on multiple lines

2023-07-23 10:04 UTC, MarcelGarus commented on compiler/frontend/src/rich_ir.rs
>      }
This inserts newlines into HIR IDs (see output in the golden files).

2023-07-23 10:04 UTC, MarcelGarus commented on packages/Examples/.goldens/fibonacci.candy/CST.txt
> +
Lots of additional newlines here too.

2023-07-23 17:27 UTC, JonasWanke commented on compiler/cli/src/debug.rs
> +            let lir = address_regex.replace_all(&lir.text, "<removed address>");
New version:

```
# Constant heap
:
<replaced address 19f5ab9aed6fbc6a>: Examples:fakeAddress
<replaced address 2ded061b072e15be>: { 0 arguments (capturing nothing) → ip-0 }
<replaced address 5a4b1729d87f7547>: "my favorite color is 0x71ec4f"
<replaced address 67941ff82bc263af>: Foo0xdeadbeef
<replaced address 6ef9df84009715c0>: "Foo0xdeadbeef"
<replaced address fdfd0ac32fb5aa09>: [67941FF82BC263AF → Foo0xdeadbeef: "my favorite color is 0x71ec4f"]

# Instructions
# Examples:fakeAddress
:
0: pushConstant <replaced address fdfd0ac32fb5aa09> [67941FF82BC263AF → Foo0xdeadbeef: "my favorite color is 0x71ec4f"]
1: popMultipleBelowTop 1
2: return
```

2023-08-03 10:17 UTC, MarcelGarus approved these changes

2023-08-03 10:34 UTC, merged