Chrono package
candy-lang/candy pull request #772
Opened 2023-10-25 12:14 UTC by skyz1

Closes: #732

This PR adds a basic `Chrono` package that supports:
1. Instants
2. Accessing the System Time
3. Durations

### Checklist

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

2023-11-02 13:01 UTC, JonasWanke requested changes

2023-11-02 13:01 UTC, JonasWanke commented on packages/Chrono/clock.candy
> +  function.run (tag.getValue clock)
```suggestion
  clock | tag.getValue | function.run
```

2023-11-02 13:01 UTC, JonasWanke commented on packages/Chrono/duration.candy
> +# Storage Format: Duration (fixedDecimal of nanoseconds)
Single octothorpes are doc comments that apply to the item above

```suggestion
## Storage Format: Duration (fixedDecimal of nanoseconds)
```

2023-11-02 13:01 UTC, JonasWanke commented on packages/Chrono/duration.candy
> +# Storage Format: Duration (fixedDecimal of nanoseconds)
Instead of starting fractions after the nanoseconds, I'd find a fixed decimal of seconds more intuitive here

2023-11-02 13:01 UTC, JonasWanke commented on packages/Chrono/duration.candy
> +# TODO: Do this without truncating division if possible
```suggestion
## TODO: Do this without truncating division if possible
```

2023-11-02 13:01 UTC, JonasWanke commented on packages/Chrono/instant.candy
> +addDuration instant dur :=
```suggestion
add instant dur :=
```

2023-11-02 13:01 UTC, JonasWanke commented on packages/Chrono/instant.candy
> +  duration.fromNanoseconds (fixedDecimal.subtract (tag.getValue instantA) (tag.getValue instantB))
We could merge these both to a single `subtract` function that acts depending on the value of the second parameter

2023-11-02 13:01 UTC, JonasWanke commented on packages/Chrono/instant.candy
> +# Storage Format: Instant (fixedDecimal of nanoseconds since the Unix Epoch)
What do you think about storing a `duration since the unix expoch` inside instead of a raw fixed decimal?

(Also, two octothorpes here)

2023-11-02 13:01 UTC, JonasWanke commented on packages/Core/text.candy
> +
These two functions belong together, so we can group by removing this empty line

```suggestion
```

2023-11-02 13:01 UTC, JonasWanke commented on packages/Core/text.candy
> +  }
We could add a function `text.repeat text times` as a reusable helper

2023-11-02 13:01 UTC, JonasWanke commented on packages/Examples/clock.candy
> +  print "It has been {now | instant.toUnixTimeDuration | duration.toText} since the start the of unix epoch"
```suggestion
  print "It has been {now | instant.toUnixTimeDuration | duration.toText} since the start the of Unix epoch"
```

2023-11-29 14:49 UTC, skyz1 commented on packages/Chrono/instant.candy
> +  duration.fromNanoseconds (fixedDecimal.subtract (tag.getValue instantA) (tag.getValue instantB))
I think it is better to keep those functions separated since the first returns an `Instant` and the second a `Duration`. I think it would be confusing if a function returned values of different types depending on the argument types.

2023-11-29 14:52 UTC, skyz1 commented on packages/Chrono/instant.candy
> +# Storage Format: Instant (fixedDecimal of nanoseconds since the Unix Epoch)
I agree with you, but this approach would be slower. Either we implement your suggestion and hope that the compiler can optimize such type tags in the future or we use the faster variant for the time being and leave a note.

2023-11-30 10:57 UTC, JonasWanke commented on packages/Chrono/instant.candy
> +# Storage Format: Instant (fixedDecimal of nanoseconds since the Unix Epoch)
Speed is not that important right now and we still have a few compiler optimizations planned, so I'd go with the cleaner, albeit slower approach

2023-11-30 10:59 UTC, JonasWanke commented on packages/Chrono/instant.candy
> +  duration.fromNanoseconds (fixedDecimal.subtract (tag.getValue instantA) (tag.getValue instantB))
Having both in the same function basically corresponds to overloading in languages like Kotlin or Java, and as a developer looking for either of those functions, `subtract` should be intuitive. I'd like to try merging these two and see if (also together with the tooling showing function results live in the editor) this suffices, and we can use that pattern in general. Otherwise, we'll revert it to two separate functions in the future.

2023-12-16 15:55 UTC, skyz1 commented
@JonasWanke Sorry for the delay, I've been very busy lately. I have addressed your remaining comments.

2023-12-19 18:27 UTC, JonasWanke requested changes
I found one bug, but the rest looks good

2023-12-19 18:27 UTC, JonasWanke commented on packages/Chrono/instant.candy
> +  duration.fromSeconds (tag.getValue instant)
The value is already a duration

```suggestion
  tag.getValue instant
```

2023-12-25 21:12 UTC, JonasWanke approved these changes

2023-12-25 21:12 UTC, merged