Refactor iterable
candy-lang/candy pull request #778
Opened 2023-10-26 18:58 UTC by MarcelGarus

Closes: #776 

### Checklist

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

2023-10-26 20:33 UTC, JonasWanke requested changes

2023-10-26 20:33 UTC, JonasWanke commented on packages/Random/rngs/pseudo/xorshift.candy
> +      { [X: getU32 0, Y: getU32 1, Z: getU32 2, W: getU32 3] }
```suggestion
    seed | iterator.fromList | iterator.all { it -> it | equals 0 }
    { [X: 0x0BAD5EED, Y: 0x0BAD5EED, Z: 0x0BAD5EED, W: 0x0BAD5EED] }
    { [X: getU32 0, Y: getU32 1, Z: getU32 2, W: getU32 3] }
```

2023-10-26 20:33 UTC, JonasWanke commented on packages/Core/iterator.candy
> +  function.is1 guard
```suggestion
  needs (function.is1 guard)
```

2023-10-26 20:33 UTC, JonasWanke commented on packages/Core/iterator.candy
> +  iterator | wrapSafe { needs False "`chunked` needs an iterator." } | windowed size size True
The tests got deleted

2023-10-26 20:33 UTC, JonasWanke commented on packages/Core/iterator.candy
> +    _ -> panicUsingGuard
```suggestion
    _ -> function.run panicUsingGuard
```

2023-10-27 00:20 UTC, MarcelGarus commented
Some notes for changes that don't fit the PR title:

- I fixed a use-after-free introduced by #745 
- I erroneously accepted https://github.com/candy-lang/candy/pull/744#discussion_r1373202603, causing failed asserts of `!self.is_negative()`

2023-10-27 12:32 UTC, MarcelGarus commented
Surprisingly, `wrapSafe` doesn't seem to impact performance too badly and it results in a much better dev experience when errors occur. That's why I'm inclined to leave it in for now.

2023-10-27 14:36 UTC, JonasWanke commented on compiler/vm/src/heap/object_inline/int.rs
> -                    lhs.bit_length()
What was the problem here? This is only called on non-negative numbers

2023-10-27 14:36 UTC, JonasWanke commented on packages/Core/iterator.candy
> +        a -> needs False "The `mapper` is bad. It should return Empty or More [item, state], but it returned this: {a}"
```suggestion
        a -> needs False "The `mapper` is bad. It should return `Empty` or `More [item, state]`, but it returned this: `{a}`"
```

2024-01-06 12:59 UTC, JonasWanke approved these changes

2024-01-06 12:59 UTC, merged